### ISSUE TITLE
项目更新了代码，也应该更新相关引用的博文

### ISSUE THREAD

**Issue by supgeek-rod** [DaoCloud/php-laravel-mysql-sample#1]
DaoCloud很棒

这篇博文中 http://open.daocloud.io/ru-he-kai-fa-yi-ge-laravel-mysql-kuang-jia-de-docker-hua-ying-yong/#
`apt-get install` 没有 `git`  
结果可想而知

**Comment by Ye-Ting** [comment]
:) ! 文档已更新。

**Comment by Ye-Ting** [comment]
:) ! 文档已更新。感谢您对我们的支持
