### ISSUE TITLE
请问一下这个repo做成的build真的可以跑起来么?

### ISSUE THREAD

**Issue by KIDJourney** [DaoCloud/php-laravel-mysql-sample#2]
已经找到的问题如下：
- `config/app.php` 中 `APP_KEY` 未设置。
- 没有进行 `php artisan migration` 。
- 几个环境变量不存在。

这个真的能跑？

**Comment by Ye-Ting** [comment]
1. APP_KEY 为环境变量需要通过 docker 运行时传入
2. migration 会在第一次访问的时候做
3. 通过 DaoCloud 云平台运行，绑定 mysql 服务就能运行

**Comment by KIDJourney** [comment]
明白了，多谢了。
